name: "[Support] DataCap Refresh Review"
description: "Issue Template for submitting a request to receive addtional DataCap for allocation"
body:
- type: markdown
  attributes:
    value: |
      # DatCap Request
      To provide/update the location of your Allocator diligence and bookkeeping repository. 
- type: input
  attributes:
    label: Organization 
    description: The name of the Allocator Organization you are wishing to request DataCap on behalf of.
  validations:
    required: true
- type: input
  attributes:
    label: JSON Number  
    description: The Application tracking JSON linked to your organization [JSON](https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators)
  validations:
    required: true
- type: dropdown
  attributes:
    label: Is the Github account being used to create this refill request issue listed as an authorized user in the JSON linked above? 
    options:
      - "Yes"
      - "No"
      - Other (please specify in comments)
  validations:
    required: true
- type: dropdown
  attributes:
    label: How many times has your pathway received a DataCap refresh review? 
    options:
      - First Time
      - 2
      - 3
      - 4
      - 5
      - 5+
  validations:
    required: true
- type: input
  attributes:
    label: Past DataCap Refresh  
    description: Please link the past Applications from any Diligence Audits
- type: dropdown
  attributes:
    label: How many clients did you distrbute DataCap to with this most recent allocation?
    options:
      - 1
      - 2
      - 3
      - 4
- type: input
  attributes:
    label: Previous Bookkeeping URL 
    description: Please link the past Bookkeeping records for the client discovery that conducted to verify the client's data met the onboarding standards of your application, and the data was stored within requirements.
  validations: 
    required: false
